spring: 
  profiles:
    active: dev
  application:
    name: consumer
  
server:
  port: 8088
            
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback-boot.xml
  path: /project/logs/microservice-springcloud/consumer
          
---
spring:
  profiles:
    active: dev
  rabbitmq:
    addresses: 192.168.0.204:5672
    username: admin
    password: 123456

eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: consumer-01
    prefer-ip-address: true